[package]
name = "speet-powerpc"
version = "0.1.0"
edition = "2024"
description.workspace = true
license-file.workspace = true

[dependencies]
wasm-encoder.workspace = true
yecta = {path = "../yecta"}
powerpc.workspace = true